#!/bin/bash

# >> Declare Color
export RED="\033[0;31m"
export GREEN="\033[0;32m"
export YELLOW="\033[0;33m"
export BLUE="\033[0;34m"
export PURPLE="\033[0;35m"
export CYAN="\033[0;36m"
export LIGHT="\033[0;37m"
export NC="\033[0m"
export RED_BG="\e[41m"

# >> Declare Debug flag
export INFO="[${YELLOW} INFO ${NC}]"
export FAIL="[${RED} FAIL ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export WAIT="[${YELLOW} WAIT ${NC}]"

clear

echo -e ""
read -p "$(echo -e "${WAIT} Input Name File : ")" nama
echo -e ""
read -p "$(echo -e "${WAIT} Input ID DRIVE : ")" idcode

wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet \
--save-cookies /tmp/cookies.txt --keep-session-cookies \
--no-check-certificate 'https://drive.google.com/uc?export=download&id=$idcode' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=$idcode" \
-O "$nama" && rm -rf /tmp/cookies.txt

sleep 5
clear

./gdrive upload /root/"$nama"

sleep 5
clear

rm -rf ./"$nama"
